import type { Metadata } from "next";
import { outfit } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased grid xl:h-screen place-items-center p-4 
        sm:p-16 xl:p-28`}
      >
        {children}
      </body>
    </html>
  );
}
